AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template S3_Website_Bucket_With_Retain_On_Delete:
  Sample template showing how to create a publicly accessible S3 bucket
  configured for website access with a deletion policy of retain on delete.
  **WARNING** This template creates an S3 bucket that will NOT be deleted when
  the stack is deleted. You will be billed for the AWS resources used if you
  create a stack from this template.
  
Parameters:
  NewBucketName:
    Type: String
    Description: Name of the bucket to create

Resources:
  TestBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref NewBucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - TestBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - TestBucket
          - DomainName
    Description: Url of S3 bucket to hold website content
  S3BucketArn:
    Value: !GetAtt 
          - TestBucket
          - Arn
    Description: Arn of S3 bucket to hold website content
  S3BucketName:
    Value: !Ref NewBucketName
    Description: Name of S3 bucket to hold website content
    Export:
      Name: s3-TemplateBucketName