AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template DynamoDB_Secondary_Indexes: Create a
  DynamoDB table with local and global secondary indexes. **WARNING** This
  template creates an Amazon DynamoDB table. You will be billed for the AWS
  resources used if you create a stack from this template.
Parameters:
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '10'
    MinValue: '5'
    MaxValue: '10000'
    ConstraintDescription: must be between 5 and 10000
  TableName:
    Description: DynamoDb Table Name
    Type: String

Resources:
  NewTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: pk_id
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi_1_sk
          AttributeType: S
        - AttributeName: gsi_2_pk
          AttributeType: S
        - AttributeName: gsi_2_sk
          AttributeType: S
        - AttributeName: gsi_3_pk
          AttributeType: S
        - AttributeName: gsi_3_sk
          AttributeType: S
        - AttributeName: item_type_debug
          AttributeType: S
      KeySchema:
        - AttributeName: pk_id
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      GlobalSecondaryIndexes:
        - IndexName: Gsi1Index
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: gsi_1_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
        - IndexName: Gsi2Index
          KeySchema:
            - AttributeName: gsi_2_pk
              KeyType: HASH
            - AttributeName: gsi_2_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
        - IndexName: Gsi3Index
          KeySchema:
            - AttributeName: gsi_3_pk
              KeyType: HASH
            - AttributeName: gsi_3_sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
        - IndexName: GsiDebugIndex
          KeySchema:
            - AttributeName: item_type_debug
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: !Ref ReadCapacityUnits
            WriteCapacityUnits: !Ref WriteCapacityUnits
      TableName: !Ref TableName
Outputs:
  TableName:
    Value: !Ref NewTable
    Description: Name of the newly created DynamoDB table
    Export:
      Name: dynamodb-TableName
  TableArn:
    Value: !GetAtt 
          - NewTable
          - Arn
    Description: Arn of the newly created DynamoDB table