export const fakeValueArrays = {
    adjustments : ['quarterly', 'monthly', 'annually'],
    terminationDates : ['end of year', 'end of month'],
    product_category_types : ['Pacht', 'Errichtung','Abkauf'],
    names : ["John", "Winnie", "Mary", "Lucy", "Brigit", "Chuck"],
    genders : ["male", "male", "female", "female", "female", "male"],
    titles : ["Mr.", "Mr.", "Mrs.", "Mrs.", "Mrs.", "Mr."],
    streets : ["Main street", "Single street", "Straight street", "Dummy street", "Elm street"],
    functions : ["Supervisor", "Sales manager", "Client manager", "Manager"],
    marital_statuses : ["single", "married", "divorced"],
    politicals : ["left wing", "right wing", "not sure"],
    cities : ["Berlin", "Zurich", "Baden-Baden", "Alzenau", "Frankfurt am Main"],
    lastNames : ["The Pooh", "Pen", "Robin", "Norris", "Kruger", "Lee", "Lang"],
    middleNames : ["Samuel", "Clark", "Bently", "Maroon", "Bright", "Roxy"],
    religions : ["catholic", "muslim", "christian", "protestant", "buddhist", "Hare Krishna", "judaite"],
    hobbies : ["horse riding", "golf", "bicycles", "motorbykes", "swimming", "sailing", "hobby? work-work-work!"],
    contact_comments : ["super contact", "ok", "forgets to pay in time", "likes to talk", "mediocre relationship"],
    supplier_names : ["Iren", "Valery", "Gabriella", "Roger", "Freddie", "Mustapha"],
    supplier_genders : ["female", "male", "female", "male", "male", "male"],
    supplier_lastNames : ["Innuendo", "Mercury", "Taylor", "May", "Kruger", "Deacon", "Meladze"],
    industry_sectors: ["Oil & Gas", "Electricity", "Water"],
    supplier_comments : ["super supplier", "ok", "forgets to deliver in time", "bad communication", "mediocre relationship"],
    building_categories: ["apartment building", "industry building", "school", "univercity", "mall"],
    inspection_maintenance_companies: ["Insp./Maint. company #1","Insp./Maint. company #2","Insp./Maint. company #3","Insp./Maint. company #4"],
    hydraulic_circuite_types: ["Drosselschaltung", "Umlenkschaltung", "Beimischschaltung (Mischventil)", "Beimischschaltung (Verteilerventil)", "Beimischschaltung (differenzdrucklosem Verteiler)"],
    distribution_classifications: ["Wärmenetz", "Stromnetz", "Gasnetz"],
    distribution_network_types: ["Erzeugerkreislauf", "Verteilerkreislauf", "Verbraucherkreislauf (immer Heizwärme)", "Zirkulationskreislauf"],
    materials: ["copper", "aluminium", "plastic"],
    manufacturers: ["Buderus", "Weishaupt", "Magra", "PEWO", "Sauter", "Huch", "Reflex Winkelmann", "Honeywell centra", "Viessmann"],
    fuel_categories: ["Gas", "Oil"],
    customer_contract_products: ["Heat", "Oil", "Gas", "Water"],
    supplier_contract_products: ["Heat delivery", "Oil delivery", "Gas delivery", "Water delivery"]
}